### ISSUE TITLE
亚瑟 AX1800 Pro要用那个呢？

### ISSUE THREAD

**Issue by papagaye744** [breeze303/openwrt-ci#1]
大佬，下载看到亚瑟有两个文件：`libwrt-qualcommax-ipq60xx-jdc_ax1800-pro-squashfs-factory.bin` 和 `libwrt-qualcommax-ipq60xx-jdcloud_ax1800-pro-squashfs-factory.bin`
有什么区别？应该用那个？

**Comment by breeze303** [comment]
uboot刷第一个web升级用第二个
