### ISSUE TITLE
usb3的kmod可以加到默认包

### ISSUE THREAD

**Issue by permheaddamage** [breeze303/openwrt-ci#16]
1. CONFIG_PACKAGE_kmod-usb-dwc3-qcom 这个比CONFIG_PACKAGE_kmod-usb-dwc2更适用这些soc
2. CONFIG_PACKAGE_kmod-usb3 这个是xchi驱动，可能已经通过某些依赖导入过了
3. CONFIG_PACKAGE_kmod-usb-storage-uas 这个是移动硬盘要用的
4. CONFIG_PACKAGE_kmod-fs-exfat和CONFIG_PACKAGE_kmod-fs-vfat是u盘的文件系统格式

**Comment by breeze303** [comment]
这种直接pr而不是提is
