### ISSUE TITLE
SSL_CTX_set_srp_username: symbol not found

### ISSUE THREAD

**Issue by ly360** [breeze303/openwrt-ci#23]
安装curl后提示SSL_CTX_set_srp_username: symbol not found

**Comment by ly360** [comment]
root@LibWrt:~# curl https://www.baidu.com
Error relocating /usr/lib/libcurl.so.4: SSL_CTX_set_srp_username: symbol not found
Error relocating /usr/lib/libcurl.so.4: SSL_CTX_set_srp_password: symbol not found

**Comment by beck023** [comment]
我刚刚也遇到了同样的问题,试过强制重新安装libcurl 也不行,网上找到的都试过了.
curl 4.ipw.cn
Error relocating /usr/lib/libcurl.so.4: SSL_CTX_set_srp_username: symbol not found
Error relocating /usr/lib/libcurl.so.4: SSL_CTX_set_srp_password: symbol not found
大佬能帮忙看看吗,是不是编译的时候有问题呀

**Comment by beck023** [comment]
忘了说了用的这个版本,R2024-10-27 04:34:59 for IPQ60XX-ALL, 机型是JDC AX1800 Pro.

**Comment by breeze303** [comment]
预编译试试
