### ISSUE TITLE
JDC-AX1800PRO 无线驱动内存泄漏

### ISSUE THREAD

**Issue by xiongyumail** [breeze303/OpenWrt-CI#24]
当打开 JDC-AX1800PRO 无线接入点后，是否有人经历过以下问题：

1. 内存缓慢逐渐减少，最终导致内存耗尽（OOM）
2. 即使使用 top 命令查看，也未发现异常的内存占用情况
3. 另一台未打开无线的设备(作为主路由)，长时间内存保持稳定，没有明显波动

**Comment by kwrum1** [comment]
运行时间 | 11h 7m 47s
可用数 651mb  
过24小时 48小时 72小时之后我再记录一次

**Comment by breeze303** [comment]
试试最新的带无线nss固件有没有这个问题

**Comment by kwrum1** [comment]
> 运行时间 | 11h 7m 47s
> 可用数 651mb  
> 过24小时 48小时 72小时之后我再记录一次 
> 

时间过去22小时
内存可用数659.66mb
版本最新6.6.32
目测排除问题

**Comment by kwrum1** [comment]
> > 运行时间 | 11h 7m 47s
> > 可用数 651mb  
> > 过24小时 48小时 72小时之后我再记录一次 
> > 
> 
> 时间过去22小时
> 内存可用数659.66mb
> 版本最新6.6.32
> 目测排除问题

早上起床653 此题终结

**Comment by breeze303** [comment]
> > > 运行时间 | 11h 7m 47s
> > > 可用数 651mb
> > > 过24小时 48小时 72小时之后我再记录一次
> > 
> > 
> > 时间过去22小时
> > 内存可用数659.66mb
> > 版本最新6.6.32
> > 目测排除问题
> 
> 早上起床653 此题终结

版本号为r1.5才是最新的

**Comment by SeamusCheng** [comment]
最新版本CPU处不显示nss是正常的吗？

**Comment by SeamusCheng** [comment]
> > > > 运行时间 | 11h 7m 47s
> > > > 可用数 651mb
> > > > 过24小时 48小时 72小时之后我再记录一次
> > > 
> > > 
> > > 时间过去22小时
> > > 内存可用数659.66mb
> > > 版本最新6.6.32
> > > 目测排除问题
> > 
> > 
> > 早上起床653 此题终结
> 
> 版本号为r1.5才是最新的

最新版本CPU处不显示nss是正常的吗？

**Comment by breeze303** [comment]
> > > > > 运行时间 | 11h 7m 47s
> > > > > 可用数 651mb
> > > > > 过24小时 48小时 72小时之后我再记录一次
> > > > 
> > > > 
> > > > 时间过去22小时
> > > > 内存可用数659.66mb
> > > > 版本最新6.6.32
> > > > 目测排除问题
> > > 
> > > 
> > > 早上起床653 此题终结
> > 
> > 
> > 版本号为r1.5才是最新的
> 
> 最新版本CPU处不显示nss是正常的吗？

正常，只是显示bug，目前还没修复
