### ISSUE TITLE
拉取了0614修改的新源码后，运行./scripts/feeds update -a报错

### ISSUE THREAD

**Issue by gddfczl** [breeze303/OpenWrt-CI#30]
git pull后，运行./scripts/feeds update -a。报错如下：
Updating feed 'nss_packages' from 'https://github.com/breeze303/nss-packages.git' ...
fatal: 无法快进，终止。
failed.
Updating feed 'sqm_scripts_nss' from 'https://github.com/qosmio/sqm-scripts-nss.git' ...
已经是最新的。

使用git fetch和git rebase依然是相同的错误。
![Uploading error.jpg…]()

**Comment by breeze303** [comment]
删除重新拉
